apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-backup-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Gi
  nfs:
    path: /cl_itfin/es-backup
    server: 192.32.2.4
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-backup-pvc
  namespace: itfin-log
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
  volumeName: es-backup-pv